-- DBUPDATE-032-0.SQL

CREATE CACHED TABLE IF NOT EXISTS T_REGISTRATION_REQUEST (REG_ID_C VARCHAR(36) NOT NULL, REG_USERNAME_C VARCHAR(50) NOT NULL, REG_EMAIL_C VARCHAR(100) NOT NULL, REG_PASSWORD_C VARCHAR(200) NOT NULL, REG_CREATEDATE_D DATETIME NOT NULL, REG_STATUS_C VARCHAR(10) NOT NULL, REG_REASON_C VARCHAR(500), REG_IDUSER_C VARCHAR(36), REG_PROCESSDATE_D DATETIME, PRIMARY KEY (REG_ID_C));

INSERT INTO T_REGISTRATION_REQUEST (REG_ID_C, REG_USERNAME_C, REG_EMAIL_C, REG_PASSWORD_C, REG_CREATEDATE_D, REG_STATUS_C) VALUES ('user1_id', 'user1', 'admin@localhost', '$2y$10$xg0EEKVUehutDI1m6qQhVeFz7SMQMl1jQzjf2KkVsR2c7aV2vyyjK', NOW(), 'PENDING');

-- Update the database version
update T_CONFIG set CFG_VALUE_C = '32' where CFG_ID_C = 'DB_VERSION';